### ISSUE TITLE
Detect OpenVZ somehow and avoid pulling in ntp

### ISSUE THREAD

**Issue by mgedmin** [ProgrammersOfVilnius/pov-admin-tools#6]
OpenVZ doesn't virtualize the system clock.  NTP doesn't work in it (you get a permission error in syslog and a stale pidfile).  It shouldn't even be installed in OpenVZ containers.

**Comment by mgedmin** [comment]
I don't think this is possible with apt dependencies.  As a workaround I use Ansible:

``` yml
- name: install NTP (except on OpenVZ containers)
  apt: name="{{ item }}" state="{{ 'present' if ansible_virtualization_type != 'openvz' or ansible_virtualization_role != 'guest' else 'absent' }}"
  with_items:
    - ntp
    - ntpdate
```
